### ISSUE TITLE
Is it safe to download?

### ISSUE THREAD

**Issue by hussamzain** [CocoaHeadsBrasil/MuteUnmuteMic#16]
Is it safe to download?
I'm trying to download this app using Google Chrome Version 78.0.3904.70 (Official Build) (64-bit).

![image](https://user-images.githubusercontent.com/42704207/67527028-d874a480-f66a-11e9-8a8f-4139109afca3.png)

**Comment by barbosa** [comment]
@hussamzain you should be good. Files attached to GitHub releases are stored in a random S3 bucket so that might be the reason why Chrome thinks this is not a trusted source. But it shouldn't be a problem.

If you're still unsure, you can also download the source and build the binary locally if you want.
